# problem: 
#   dim: 3
#   min_x: -10
#   max_x: 10
  

algorithm:
  max_iter: 1000
  N: 50
  min_w: 0.9
  max_w:  1.2
  c1: 1.49445
  c2: 1.49445
  min_v: -0.2 * (max_x - min_x)
  max_v: 0.2 * (max_x - min_x)
  # r1: ngẫu nhiên [0, 1]
  # r2: ngẫu nhiên [0, 1]
  